<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <RootNamespace>Bonsai.Standard</RootNamespace>
    <AssemblyName>BonsaiStandardAssembly</AssemblyName>
    <Nullable>disable</Nullable>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Unity3D.UnityEngine" Version="2020.3.21" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Core/Bonsai.Core.csproj" />
  </ItemGroup>
</Project>
